import { Itinerary, ItineraryStop, ReplaceFilterPreset } from './types';
import { RIYADH_PLACES } from './data/riyadhPlaces';

// Helper to get place by ID safely
const getPlace = (id: number) => {
  const p = RIYADH_PLACES.find((item) => item.id === id);
  if (!p) throw new Error(`Place ID ${id} not found in riyadh_places.json`);
  return p;
};

const place1 = getPlace(1); // المتحف الوطني السعودي
const place4 = getPlace(4); // الدرعية
const place6 = getPlace(6); // سوق الزل
const place3 = getPlace(3); // بوليفارد رياض سيتي

export const INITIAL_MOCK_ITINERARY: Itinerary = {
  id: 'riyadh-heritage-modern-1',
  tripTitleAr: 'مسار الرياض التاريخي والحديث المتكيف',
  tripTitleEn: 'Adaptive Historic & Modern Riyadh Trail',
  totalDurationMinutes: 360,
  summaryAr: 'مسار يومي متكامل يجمع بين الثقافة التراثية في المتحف الوطني، جولة الدرعية، تسوق سوق الزل التراثي، وفعاليات البوليفارد.',
  summaryEn: 'Comprehensive day trip covering the National Museum, Diriyah heritage, Al Zal Market, and Boulevard Riyadh City.',
  stops: [
    {
      id: 'stop-1',
      order: 1,
      placeId: place1.id,
      nameAr: place1.name_ar,
      nameEn: place1.name_en,
      category: place1.category,
      startTime: '16:00',
      endTime: '17:30',
      durationMinutes: place1.duration_minutes,
      isIndoor: place1.indoor,
      crowdLevel: 'low',
      walkingDistanceMeters: 150,
      location: {
        lat: place1.latitude,
        lng: place1.longitude,
        addressAr: 'حي المربع، وسط الرياض',
        addressEn: 'Al Murabba Dist, Central Riyadh',
      },
      status: 'completed',
      amenities: ['تكييف عالي', 'عربات أطفال', 'مصلى مغلق', 'مواقف واسعة'],
      descriptionAr: 'جولة تاريخية مكيفة بالكامل عبر أروقة المتحف الوطني، تستعرض تاريخ المملكة الثري في أجواء باردة ومريحة للعوائل.',
      descriptionEn: 'A fully air-conditioned historical tour through the National Museum displaying rich Saudi heritage.',
    },
    {
      id: 'stop-2',
      order: 2,
      placeId: place4.id,
      nameAr: place4.name_ar,
      nameEn: place4.name_en,
      category: place4.category,
      startTime: '17:45',
      endTime: '18:45',
      durationMinutes: 60,
      isIndoor: place4.indoor,
      crowdLevel: 'moderate',
      walkingDistanceMeters: 200,
      location: {
        lat: place4.latitude,
        lng: place4.longitude,
        addressAr: 'الدرعية التاريخية، الرياض',
        addressEn: 'Historic Diriyah, Riyadh',
      },
      status: 'current',
      amenities: ['معالم تاريخية', 'جلسات خارجية', 'مدخل كراسي متحركة', 'قريب من جامع البجيري'],
      prayerBuffer: {
        prayerNameAr: 'المغرب',
        prayerNameEn: 'Maghrib',
        time: '18:10',
        nearestMosqueDistanceMeters: 50,
      },
      descriptionAr: 'جولة تراثية وثقافية بجوار مطل الطريف التاريخي، مع فاصل زمني مهيأ لصلاة المغرب في جامع البجيري الكبير.',
      descriptionEn: 'Heritage cultural walk near At-Turaif, featuring a built-in buffer for Maghrib prayer at Bujairi Grand Mosque.',
    },
    {
      id: 'stop-3',
      order: 3,
      placeId: place6.id,
      nameAr: place6.name_ar,
      nameEn: place6.name_en,
      category: place6.category,
      startTime: '19:00',
      endTime: '20:15',
      durationMinutes: 75,
      isIndoor: place6.indoor,
      crowdLevel: 'moderate',
      walkingDistanceMeters: 350,
      location: {
        lat: place6.latitude,
        lng: place6.longitude,
        addressAr: 'الديرة، الرياض القديمة',
        addressEn: 'Al Deira, Historic Old Riyadh',
      },
      status: 'upcoming',
      amenities: ['مظلات مسائية', 'بخور وعطور', 'تحف وهدايا', 'مناسب لكبار السن'],
      prayerBuffer: {
        prayerNameAr: 'العشاء',
        prayerNameEn: 'Isha',
        time: '19:40',
        nearestMosqueDistanceMeters: 120,
      },
      descriptionAr: 'تسوق تراثي مسائي ممتع بين ممرات البخور والسجاد الشعبي بعد انخفاض درجات الحرارة المسائية.',
      descriptionEn: 'Enjoyable evening traditional shopping amidst incense and carpet stalls after daytime heat subsides.',
    },
    {
      id: 'stop-4',
      order: 4,
      placeId: place3.id,
      nameAr: place3.name_ar,
      nameEn: place3.name_en,
      category: place3.category,
      startTime: '20:30',
      endTime: '22:00',
      durationMinutes: 90,
      isIndoor: place3.indoor,
      crowdLevel: 'high',
      walkingDistanceMeters: 250,
      location: {
        lat: place3.latitude,
        lng: place3.longitude,
        addressAr: 'حطين، شمال الرياض',
        addressEn: 'Hittin, North Riyadh',
      },
      status: 'upcoming',
      amenities: ['فعاليات ترفيهية', 'مطاعم فاخرة', 'خدمة صف السيارات', 'عروض ضوئية'],
      descriptionAr: 'تجربة ترفيهية مسائية حيوية في بوليفارد رياض سيتي تضم مطاعم وفعاليات مناسبة لجميع الأفراد.',
      descriptionEn: 'Lively evening entertainment experience in Boulevard Riyadh City with food and activities.',
    },
  ],
};

const place9 = getPlace(9);  // واجهة روشن
const place5 = getPlace(5);  // حديقة السلام
const place2 = getPlace(2);  // برج المملكة
const place10 = getPlace(10); // ذا زون
const place7 = getPlace(7);  // يو ووك

// Preset Alternatives for Stop Replacement Modal using canonical riyadh_places.json
export const REPLACE_OPTIONS_DATABASE: Record<ReplaceFilterPreset, ItineraryStop> = {
  similar: {
    id: 'alt-similar-1',
    order: 2,
    placeId: place9.id,
    nameAr: place9.name_ar,
    nameEn: place9.name_en,
    category: place9.category,
    startTime: '17:45',
    endTime: '18:45',
    durationMinutes: place9.duration_minutes,
    isIndoor: place9.indoor,
    crowdLevel: 'moderate',
    walkingDistanceMeters: 180,
    location: {
      lat: place9.latitude,
      lng: place9.longitude,
      addressAr: 'طريق المطار، الرياض',
      addressEn: 'Airport Road, Riyadh',
    },
    status: 'current',
    amenities: ['مطاعم ومقاهي', 'مساحات مفتوحة', 'ممشى حديث'],
    descriptionAr: 'وجهة ترفيهية مميزة تضم مقاهي ومطاعم حديثة مع أداء ترفيهي وأجواء مسائية ممتعة.',
    descriptionEn: 'Vibrant entertainment destination featuring modern cafes, dining, and enjoyable evening walking areas.',
  },
  closer: {
    id: 'alt-closer-1',
    order: 2,
    placeId: place5.id,
    nameAr: place5.name_ar,
    nameEn: place5.name_en,
    category: place5.category,
    startTime: '17:40',
    endTime: '18:40',
    durationMinutes: place5.duration_minutes,
    isIndoor: place5.indoor,
    crowdLevel: 'low',
    walkingDistanceMeters: 60,
    location: {
      lat: place5.latitude,
      lng: place5.longitude,
      addressAr: 'حي السلام، وسط الرياض',
      addressEn: 'Salam Dist, Central Riyadh',
    },
    status: 'current',
    amenities: ['مساحات خضراء', 'بحيرة مائية', 'مناسب للعائلات'],
    descriptionAr: 'حديقة طبيعية هادئة بوسط الرياض توفر مساحات خضراء مريحة وقريبة جداً من المحطة السابقة.',
    descriptionEn: 'A tranquil park in central Riyadh offering green spaces and pleasant walking routes.',
  },
  indoor: {
    id: 'alt-indoor-1',
    order: 2,
    placeId: place2.id,
    nameAr: place2.name_ar,
    nameEn: place2.name_en,
    category: place2.category,
    startTime: '17:45',
    endTime: '18:45',
    durationMinutes: place2.duration_minutes,
    isIndoor: place2.indoor,
    crowdLevel: 'low',
    walkingDistanceMeters: 100,
    location: {
      lat: place2.latitude,
      lng: place2.longitude,
      addressAr: 'طريق الملك فهد، العليا',
      addressEn: 'King Fahd Rd, Al Olaya',
    },
    status: 'current',
    amenities: ['تكييف كامل', 'جسر المشاهدة', 'مواقف مغطاة'],
    descriptionAr: 'معلم داخلي مكيف بالكامل يتيح الاستمتاع بإطلالة بانورامية وتجربة تسوق راقية بعيداً عن حرارة الجو.',
    descriptionEn: 'Fully air-conditioned landmark offering panoramic sky bridge views and indoor comfort.',
  },
  less_crowded: {
    id: 'alt-less-crowded-1',
    order: 2,
    placeId: place10.id,
    nameAr: place10.name_ar,
    nameEn: place10.name_en,
    category: place10.category,
    startTime: '17:45',
    endTime: '18:45',
    durationMinutes: place10.duration_minutes,
    isIndoor: place10.indoor,
    crowdLevel: 'low',
    walkingDistanceMeters: 120,
    location: {
      lat: place10.latitude,
      lng: place10.longitude,
      addressAr: 'شارع التخصصي، المحمدية',
      addressEn: 'Takhassusi St, Al Mohammadiya',
    },
    status: 'current',
    amenities: ['هدوء ممتع', 'جلسات فاخرة', 'نافورات مائية'],
    descriptionAr: 'وجهة طعام ومقاهي هادئة تتميز بنوافير مائية وأجواء قليلة الازدحام لمشاوير مريحة.',
    descriptionEn: 'A serene dining and cafe square featuring outdoor fountains and low crowd levels.',
  },
  different_activity: {
    id: 'alt-different-1',
    order: 2,
    placeId: place7.id,
    nameAr: place7.name_ar,
    nameEn: place7.name_en,
    category: place7.category,
    startTime: '17:45',
    endTime: '18:45',
    durationMinutes: place7.duration_minutes,
    isIndoor: place7.indoor,
    crowdLevel: 'moderate',
    walkingDistanceMeters: 180,
    location: {
      lat: place7.latitude,
      lng: place7.longitude,
      addressAr: 'طريق الأمير تركي بن عبد العزيز الأول',
      addressEn: 'Prince Turki Al Awwal Rd',
    },
    status: 'current',
    amenities: ['ممشى مفتوح', 'متاجر متنوعة', 'سينما ومقاهي'],
    descriptionAr: 'تغيير النشاط إلى جولة مشي وتسوق مفتوحة في ممر يو ووك الحديث المليء بالمتاجر.',
    descriptionEn: 'A fresh walking and shopping experience along the vibrant outdoor promenade of U Walk.',
  },
};
